# Welcome to Jekyll!

# Theme Settings
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
title: "Ghazaleh Ranjbaran"
title_separator: "-"
name: "Ghazaleh Ranjbaran"
description: "AI & Data Science Specialist"
url: "https://ghazalehran.github.io"
baseurl: "" # No subpath
repository: "ghazalehran/ghazalehran.github.io"
teaser: "/assets/images/500x300.png"
logo: "/assets/images/logo.png"
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: true
copyright: "Ghazaleh Ranjbaran"
comments:
  provider: false

# Analytics
analytics:
  provider: false

# Author Information
author:
  name: "Ghazaleh Ranjbaran"
  avatar: "/assets/images/profile-photo-1.jpg"
  bio: "AI & Data Science Specialist"
  location: "Montreal, Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ghazaleh-ranjbaran"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ghazalehran"

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ghazalehran"

# Include/Exclude Files
include:
  - .htaccess
  - _pages
exclude:
  - node_modules
  - vendor
  - tmp
  - /test
keep_files:
  - .git
  - .svn

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "America/Toronto"

# Pagination for Blog Posts
paginate_path: "/blog/page:num/"
pagination:
  collection: 'posts'
  per_page: 10
  permalink: '/blog/page/:num/'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Homepage Settings
layout: splash # Set homepage layout
feature_row: # Define homepage features
  - image_path: /assets/images/portfolio.jpg
    title: "Portfolio"
    url: /portfolio/
    btn_label: "View Portfolio"
    btn_class: "btn--primary"
  - image_path: /assets/images/blog.jpg
    title: "Blog"
    url: /blog/
    btn_label: "Visit Blog"
    btn_class: "btn--primary"
  - image_path: /assets/images/resume.jpg
    title: "Resume"
    url: /resume/
    btn_label: "View Resume"
    btn_class: "btn--primary"

# Search
search: true
search_provider: lunr
